apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: nginx
          volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          hostPath:
            path: /vagrant/config/app1/index
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      
      targetPort: 80
