apiVersion: apps/v1
kind: Deployment
metadata:
  name: anajmi-app-deployment
  labels:
    app: anajmi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anajmi
  template:
    metadata:
      labels:
        app: anajmi
    spec:
      containers:
      - name: anajmi
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
