Vagrant.configure("2") do |config|
  
  config.vm.define "nel-brigS" do |control|
    control.vm.box = "debian/bookworm64"
    control.vm.hostname = "nel-brigS"
    control.vm.network "private_network", ip: "192.168.56.11"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "nel-brigS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/ServerScript.sh"
  end
end

