Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "nel-brigS" do |control|
    control.vm.hostname = "nel-brigS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "nel-brigS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.provision "shell", path: "scripts/ServerScript.sh"
  end

  config.vm.define "nel-brigSW" do |control|
    control.vm.hostname = "nel-brigSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "nel-brigSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.provision "shell", path: "scripts/WorkerScript.sh"
  end

end
