apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: nginx
          volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          hostPath:
            path: /vagrant/config/app3/index
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
